### ISSUE TITLE
guest user

### ISSUE THREAD

**Issue by codyborders** [codyborders/abandoned_camel_coffee_mercantile#26]
As a visitor when I have items in my cart
    And when I visit "/cart"
    I should not see an option to "Checkout"
    I should see an option to "Login or Create Account to Checkout"
    After I create an account
    And I visit "/cart
    Then I should see all of the data that was there when I was not logged in
    When I click "Logout"
    Then I should see see "Login"
    And I should not see "Logout"

**Comment by Ryanspink1** [comment]
Complete except for the checkout button, the logic is in place and all it needs is a working link to checkout within the else statement on cart index.
